<a href="https://colab.research.google.com/github/FarhanMS123/NeuralNetworkMemorandum/blob/main/examples/test_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python
Ref:
- https://udemy.com/course/python-for-data-science-and-machine-learning-bootcamp

In [2]:
import numpy as np

print([2,3,4,5] * 3)
# print([2,3,4,5] * [3])
# print([2,3,4,5] + 2)
print([2,3,4,5] + [2])
# print([2,3,4,5] / 3)
# print([2,3,4,5] / [2,3,4,5])
print(np.array([2,3,4,5]) * 3)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]
[2, 3, 4, 5, 2]
[ 6  9 12 15]


In [3]:
# print({2,3,3,3,2,2,3,4,5,4,4,4,5,5,5} + {7,7,7,7,2,2,2,3,3,3})
# print({2,3,3,3,2,2,3,4,5,4,4,4,5,5,5} * 2)
print("Hello" == 'Hello')
# print(False || True)
print(False or True and True)

True
True


In [4]:
seq = range(3,12)
print(seq)
print(list(seq))

for x in seq:
  print(x)

list_comprehension = [x**2 for x in seq]
print(list_comprehension)

range(3, 12)
[3, 4, 5, 6, 7, 8, 9, 10, 11]
3
4
5
6
7
8
9
10
11
[9, 16, 25, 36, 49, 64, 81, 100, 121]


In [5]:
def square(x):
  """
  This is DOCSTRING
  Shift + Tab
  Ctrl + Space
  """
  return x**2

square

<function __main__.square(x)>

In [6]:
def square2(x):
  return x**2
square2

<function __main__.square2(x)>

In [7]:
"""
This is DOCSTRING
Shift + Tab
Ctrl + Space
"""
square = lambda x: x**2
square

<function __main__.<lambda>(x)>

In [8]:
def abcd(): return 2**2
print(abcd())
print(2 in [1,2,3,4])

for a,b in [(1,2),(3,4),(5,6)]:
  print(b,a)

4
True
2 1
4 3
6 5


# Test NumPy

In [19]:
import numpy as np
print(np.arange(2,12,1.1))
print(np.zeros(4))
print(np.ones(4))
print(np.linspace(2,3,100))

[ 2.   3.1  4.2  5.3  6.4  7.5  8.6  9.7 10.8 11.9]
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2.         2.01010101 2.02020202 2.03030303 2.04040404 2.05050505
 2.06060606 2.07070707 2.08080808 2.09090909 2.1010101  2.11111111
 2.12121212 2.13131313 2.14141414 2.15151515 2.16161616 2.17171717
 2.18181818 2.19191919 2.2020202  2.21212121 2.22222222 2.23232323
 2.24242424 2.25252525 2.26262626 2.27272727 2.28282828 2.29292929
 2.3030303  2.31313131 2.32323232 2.33333333 2.34343434 2.35353535
 2.36363636 2.37373737 2.38383838 2.39393939 2.4040404  2.41414141
 2.42424242 2.43434343 2.44444444 2.45454545 2.46464646 2.47474747
 2.48484848 2.49494949 2.50505051 2.51515152 2.52525253 2.53535354
 2.54545455 2.55555556 2.56565657 2.57575758 2.58585859 2.5959596
 2.60606061 2.61616162 2.62626263 2.63636364 2.64646465 2.65656566
 2.66666667 2.67676768 2.68686869 2.6969697  2.70707071 2.71717172
 2.72727273 2.73737374 2.74747475 2.75757576 2.76767677 2.77777778
 2.78787879 2.7979798  2.80808081 2.81818182 2.828

In [23]:
c = np.random.randn(2,3,4)
print(c)
print(c.max())
print(c.argmax())
print(c[8])

[[[-0.27519263 -0.90281689 -0.83661485  0.57140059]
  [ 1.79975154  2.02040544 -0.40077441 -0.19948516]
  [ 1.54521215 -0.16634643  0.10123841 -0.97421869]]

 [[ 0.14952664 -1.24584564  0.67562763 -1.6009643 ]
  [-2.10873066  0.26708976 -0.71231891  0.7773374 ]
  [ 0.44693066 -0.06728871  1.22701707  0.12082278]]]
2.0204054429439977
5


In [25]:
d = np.array([1,2,3,4,5])
# d.reshape(3,3)

In [38]:
c = list(range(0,20))
d = np.arange(0, 20)
print(c)
print(d)
print(d[7:18])
print(c[7:18])
# a = 3:12
# print(3:12)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 7  8  9 10 11 12 13 14 15 16 17]
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]


In [93]:
c = [
  list(range(3+(x*x), 8+(x*x))) for x in range(2,11)
]

print(c)
print(c[2:4])
# print(c[2][2,3])
# print(c[2:4][0,1])
print(c[3:6])

print("=====")

d = np.random.randint(7,52256, (4,4))
print(d)
print(d[2:4, 0:3])
print(d[1,2])
print(d[2:4][1,0])

print("====")
# print([2,3,4,5,6,7,8,9,10] < 6)
print(np.array([2,3,4,5,6,7,8,9,10]) < 6)

[[7, 8, 9, 10, 11], [12, 13, 14, 15, 16], [19, 20, 21, 22, 23], [28, 29, 30, 31, 32], [39, 40, 41, 42, 43], [52, 53, 54, 55, 56], [67, 68, 69, 70, 71], [84, 85, 86, 87, 88], [103, 104, 105, 106, 107]]
[[19, 20, 21, 22, 23], [28, 29, 30, 31, 32]]
[[28, 29, 30, 31, 32], [39, 40, 41, 42, 43], [52, 53, 54, 55, 56]]
=====
[[ 9043 45233 17255 42643]
 [27020 24453 38699 45713]
 [ 5627 35316 34742 21695]
 [16194 47420 22268 18613]]
[[ 5627 35316 34742]
 [16194 47420 22268]]
38699
16194
====
[ True  True  True  True False False False False False]
