<a href="https://colab.research.google.com/github/FarhanMS123/NeuralNetworkMemorandum/blob/main/experiments/test_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python
Ref:
- https://udemy.com/course/python-for-data-science-and-machine-learning-bootcamp

In [2]:
import numpy as np

print([2,3,4,5] * 3)
# print([2,3,4,5] * [3])
# print([2,3,4,5] + 2)
print([2,3,4,5] + [2])
# print([2,3,4,5] / 3)
# print([2,3,4,5] / [2,3,4,5])
print(np.array([2,3,4,5]) * 3)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]
[2, 3, 4, 5, 2]
[ 6  9 12 15]


In [3]:
# print({2,3,3,3,2,2,3,4,5,4,4,4,5,5,5} + {7,7,7,7,2,2,2,3,3,3})
# print({2,3,3,3,2,2,3,4,5,4,4,4,5,5,5} * 2)
print("Hello" == 'Hello')
# print(False || True)
print(False or True and True)

True
True


In [4]:
seq = range(3,12)
print(seq)
print(list(seq))

for x in seq:
  print(x)

list_comprehension = [x**2 for x in seq]
print(list_comprehension)

range(3, 12)
[3, 4, 5, 6, 7, 8, 9, 10, 11]
3
4
5
6
7
8
9
10
11
[9, 16, 25, 36, 49, 64, 81, 100, 121]


In [5]:
def square(x):
  """
  This is DOCSTRING
  Shift + Tab
  Ctrl + Space
  """
  return x**2

square

<function __main__.square(x)>

In [6]:
def square2(x):
  return x**2
square2

<function __main__.square2(x)>

In [7]:
"""
This is DOCSTRING
Shift + Tab
Ctrl + Space
"""
square = lambda x: x**2
square

<function __main__.<lambda>(x)>

In [8]:
def abcd(): return 2**2
print(abcd())
print(2 in [1,2,3,4])

for a,b in [(1,2),(3,4),(5,6)]:
  print(b,a)

4
True
2 1
4 3
6 5


# Test NumPy

In [19]:
import numpy as np
print(np.arange(2,12,1.1))
print(np.zeros(4))
print(np.ones(4))
print(np.linspace(2,3,100))

[ 2.   3.1  4.2  5.3  6.4  7.5  8.6  9.7 10.8 11.9]
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2.         2.01010101 2.02020202 2.03030303 2.04040404 2.05050505
 2.06060606 2.07070707 2.08080808 2.09090909 2.1010101  2.11111111
 2.12121212 2.13131313 2.14141414 2.15151515 2.16161616 2.17171717
 2.18181818 2.19191919 2.2020202  2.21212121 2.22222222 2.23232323
 2.24242424 2.25252525 2.26262626 2.27272727 2.28282828 2.29292929
 2.3030303  2.31313131 2.32323232 2.33333333 2.34343434 2.35353535
 2.36363636 2.37373737 2.38383838 2.39393939 2.4040404  2.41414141
 2.42424242 2.43434343 2.44444444 2.45454545 2.46464646 2.47474747
 2.48484848 2.49494949 2.50505051 2.51515152 2.52525253 2.53535354
 2.54545455 2.55555556 2.56565657 2.57575758 2.58585859 2.5959596
 2.60606061 2.61616162 2.62626263 2.63636364 2.64646465 2.65656566
 2.66666667 2.67676768 2.68686869 2.6969697  2.70707071 2.71717172
 2.72727273 2.73737374 2.74747475 2.75757576 2.76767677 2.77777778
 2.78787879 2.7979798  2.80808081 2.81818182 2.828

In [23]:
c = np.random.randn(2,3,4)
print(c)
print(c.max())
print(c.argmax())
print(c[8])

[[[-0.27519263 -0.90281689 -0.83661485  0.57140059]
  [ 1.79975154  2.02040544 -0.40077441 -0.19948516]
  [ 1.54521215 -0.16634643  0.10123841 -0.97421869]]

 [[ 0.14952664 -1.24584564  0.67562763 -1.6009643 ]
  [-2.10873066  0.26708976 -0.71231891  0.7773374 ]
  [ 0.44693066 -0.06728871  1.22701707  0.12082278]]]
2.0204054429439977
5


In [25]:
d = np.array([1,2,3,4,5])
# d.reshape(3,3)

In [38]:
c = list(range(0,20))
d = np.arange(0, 20)
print(c)
print(d)
print(d[7:18])
print(c[7:18])
# a = 3:12
# print(3:12)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 7  8  9 10 11 12 13 14 15 16 17]
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]


In [44]:
c = [
  list(range(3+(x*x), 8+(x*x))) for x in range(2,11)
]

print(c)
print(c[2:4])
# print(c[2][2,3])
# print(c[2:4][0,1])
print(c[3:6])

print("=====")

d = np.random.randint(7,52256, (4,4))
print(d)
print(d[2:4, 0:3])
print(d[1,2])
print(d[2:4][1,0])

print("====")
# print([2,3,4,5,6,7,8,9,10] < 6)
print(np.array([2,3,4,5,6,7,8,9,10]) < 6)

[[7, 8, 9, 10, 11], [12, 13, 14, 15, 16], [19, 20, 21, 22, 23], [28, 29, 30, 31, 32], [39, 40, 41, 42, 43], [52, 53, 54, 55, 56], [67, 68, 69, 70, 71], [84, 85, 86, 87, 88], [103, 104, 105, 106, 107]]
[[19, 20, 21, 22, 23], [28, 29, 30, 31, 32]]
[[28, 29, 30, 31, 32], [39, 40, 41, 42, 43], [52, 53, 54, 55, 56]]
=====
[[51681 11056 38357 34673]
 [ 9933 27620 40817 46173]
 [36298 41359 30700 43981]
 [39726 29964 27359 52033]]
[[36298 41359 30700]
 [39726 29964 27359]]
40817
39726
====
[ True  True  True  True False False False False False]


In [99]:
print([2,3,4] + [5,6,7])
print(np.array([2,3,4]) + np.array([5,6,7]))
# print([2,3,4] - [5,6,7])
print(np.array([2,3,4]) - np.array([5,6,7]))
# print([2,3,4] * [5,6,7])
print(np.array([2,3,4]) * np.array([5,6,7]))

[2, 3, 4, 5, 6, 7]
[ 7  9 11]
[-3 -3 -3]
[10 18 28]


- https://numpy.org/doc/stable/reference/ufuncs.html
- https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

In [111]:
# print([2,3,4] + 100)
print(np.array([2,3,4]) + 100)
# print([2,3,4] - 100)
print(np.array([2,3,4]) - 100)
print([2,3,4] * 4)
print(np.array([2,3,4]) * 100)
# print([2,3,4] ** 5)
print(np.array([2,3,4]) ** 5)

[102 103 104]
[-98 -97 -96]
[2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4]
[200 300 400]
[  32  243 1024]


In [ ]:
np.std
np.sum

# Basic Pandas

In [5]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a', 'b', 'c']
my_data = [10, 20, 30]
aee = np.array(my_data)
d = {
    'a': 10,
    'b': 20,
    'c': 30
}

In [6]:
ser1 = pd.Series(my_data, labels)
ser1 + 7

a    17
b    27
c    37
dtype: int64

In [9]:
np.random.seed(101)
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [40]:
# pd.DataFrame(np.random.randn(3,3,3), ['A', 'B', 'C'], ['X', 'Y', 'Z'])
ser = pd.DataFrame(np.random.randn(5,4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])
print(ser)
# print(ser['A'])
print(ser['X'])
# print(ser[1])
print(ser.X)
print(ser['X']['A'])
# print(ser['X','A'])
# print(ser['X','Y'])
print(ser[['X','Y']])
# print(ser['X'])
print(ser.shape)

          W         X         Y         Z
A -1.975561 -1.746010 -1.905228 -0.271117
B  0.278761 -0.664855  1.119901 -0.297896
C  0.822210 -0.434672 -0.192274  2.144336
D  0.601143 -0.249884  0.146623 -1.749671
E  1.082361  0.103183  0.130141  0.198255
A   -1.746010
B   -0.664855
C   -0.434672
D   -0.249884
E    0.103183
Name: X, dtype: float64
A   -1.746010
B   -0.664855
C   -0.434672
D   -0.249884
E    0.103183
Name: X, dtype: float64
-1.746009901965017
          X         Y
A -1.746010 -1.905228
B -0.664855  1.119901
C -0.434672 -0.192274
D -0.249884  0.146623
E  0.103183  0.130141
(5, 4)


In [34]:
print(ser.loc['B'])
print(ser.iloc[1])
print(ser.loc['B','Y'])
print(ser.loc['B':'D','Y':'Z'])
print(ser.loc[['B','C'],['Y', 'Z']])

W   -0.273343
X   -0.220944
Y    0.686967
Z   -1.154717
Name: B, dtype: float64
W   -0.273343
X   -0.220944
Y    0.686967
Z   -1.154717
Name: B, dtype: float64
0.6869666375167397
          Y         Z
B  0.686967 -1.154717
C -0.001107  1.874769
D  1.062296  0.229439
          Y         Z
B  0.686967 -1.154717
C -0.001107  1.874769


In [42]:
print(ser > 0)
print(ser[ser > 0])
print()
print(ser['W'] > 0)
print(ser[ser['W'] > 0])

       W      X      Y      Z
A  False  False  False  False
B   True  False   True  False
C   True  False  False   True
D   True  False   True  False
E   True   True   True   True
          W         X         Y         Z
A       NaN       NaN       NaN       NaN
B  0.278761       NaN  1.119901       NaN
C  0.822210       NaN       NaN  2.144336
D  0.601143       NaN  0.146623       NaN
E  1.082361  0.103183  0.130141  0.198255

A    False
B     True
C     True
D     True
E     True
Name: W, dtype: bool
          W         X         Y         Z
B  0.278761 -0.664855  1.119901 -0.297896
C  0.822210 -0.434672 -0.192274  2.144336
D  0.601143 -0.249884  0.146623 -1.749671
E  1.082361  0.103183  0.130141  0.198255


## Higher Hirarchy

In [6]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index_zip = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index_zip)

In [11]:
print(hier_index_zip)
df = pd.DataFrame(np.random.randn(6,2), hier_index, ['A','B'])
df

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]


A         B
G1 1 -0.612011  0.578059
   2  0.767272  0.622372
   3 -1.487161  1.697693
G2 1 -0.251855  0.225562
   2 -0.395082 -1.821441
   3 -1.118749 -0.871049

In [28]:
print(df['A'])
# print(df['A','G1'])
print(df.loc['G1'])
print(df.loc['G1','A'])
print(df.loc['G1','A'][1])
print(df.loc['G1'].loc[1,'A'])
print(df.xs(1, level=1))

G1  1   -0.612011
    2    0.767272
    3   -1.487161
G2  1   -0.251855
    2   -0.395082
    3   -1.118749
Name: A, dtype: float64
          A         B
1 -0.612011  0.578059
2  0.767272  0.622372
3 -1.487161  1.697693
1   -0.612011
2    0.767272
3   -1.487161
Name: A, dtype: float64
-0.6120109664799464
-0.6120109664799464
           A         B
G1 -0.612011  0.578059
G2 -0.251855  0.225562


In [39]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [48]:
df = pd.DataFrame(data)
print(df)

gb = df.groupby('Company')
print(list(gb))
# print(gb.mean(numeric_only=True))
# print(gb.sum(numeric_only=True))
# print(gb.std(numeric_only=True))
# print(gb.count())
# print(gb.max())
# print(gb.describe().transpose())
print(gb.describe())

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350
[('FB',   Company Person  Sales
4      FB   Carl    243
5      FB  Sarah    350), ('GOOG',   Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120), ('MSFT',   Company   Person  Sales
2    MSFT      Amy    340
3    MSFT  Vanessa    124)]
        Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0


In [ ]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

print(pd.concat([df1,df2,df3]))
# print(pd.concat([df1,df2,df3], axis=1))

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN 

In [3]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

print(df)
print(df.head())
print()
print(df['col2'].unique())
print(df['col2'].nunique())
print(df['col2'].value_counts())
print()
print((df['col1'] > 2) & (df['col2'] == 444))
print(df[(df['col1'] > 2) & (df['col2'] == 444)])
print()
print(df['col1'].apply(lambda x: x * 2))
print(df['col1'].apply(lambda x: x * 2).sum())

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz
   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

[444 555 666]
3
col2
444    2
555    1
666    1
Name: count, dtype: int64

0    False
1    False
2    False
3     True
dtype: bool
   col1  col2 col3
3     4   444  xyz

0    2
1    4
2    6
3    8
Name: col1, dtype: int64
20


In [4]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

print(df)
print()
print(df.pivot_table(values='D', index=['A', 'B'], columns=['C']))

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN


## Input & Output

In [ ]:
%pwd
# %conda install xlrd
# %conda install sqlalchemy
# %conda install lxml
# %conda install html5lib
# %conda install BeautifulSoup4

'c:\\Users\\farha\\Downloads\\project\\NeuralNetworkMemorandum\\experiments'

In [18]:
import pandas as pd

df = pd.read_csv('example.csv')
print(df)

df.to_csv("._temp_output_test1.csv", index=False)
print(pd.read_csv("._temp_output_test1.csv"))

df.to_csv("._temp_output_test2.csv")
print(pd.read_csv("._temp_output_test2.csv"))

df_xlsx = pd.read_excel("Excel_Sample.xlsx", sheet_name='Sheet1')
print(df_xlsx)

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15
   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15


In [16]:
df_html = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')
print(df_html)

[                               Bank Name               City          State  \
0     The First National Bank of Lindsay            Lindsay       Oklahoma   
1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania   
2                          Citizens Bank           Sac City           Iowa   
3               Heartland Tri-State Bank            Elkhart         Kansas   
4                    First Republic Bank      San Francisco     California   
5                         Signature Bank           New York       New York   
6                    Silicon Valley Bank        Santa Clara     California   
7                      Almena State Bank             Almena         Kansas   
8             First City Bank of Florida  Fort Walton Beach        Florida   
9                   The First State Bank      Barboursville  West Virginia   

    Cert                 Aquiring Institution      Closing Date  \
0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024   
1  273

In [15]:
df[0].head()

Bank Name           City         State   Cert  \
0     The First National Bank of Lindsay        Lindsay      Oklahoma   4134   
1  Republic First Bank dba Republic Bank   Philadelphia  Pennsylvania  27332   
2                          Citizens Bank       Sac City          Iowa   8758   
3               Heartland Tri-State Bank        Elkhart        Kansas  25851   
4                    First Republic Bank  San Francisco    California  59017   

                 Aquiring Institution      Closing Date  Fund  Sort ascending  
0  First Bank & Trust Co., Duncan, OK  October 18, 2024                 10547  
1   Fulton Bank, National Association    April 26, 2024                 10546  
2           Iowa Trust & Savings Bank  November 3, 2023                 10545  
3              Dream First Bank, N.A.     July 28, 2023                 10544  
4           JPMorgan Chase Bank, N.A.       May 1, 2023                 10543

In [21]:
from sqlalchemy import create_engine
conn = create_engine('sqlite:///:memory:')
df.to_sql('my_table', conn)

print(conn)
print(pd.read_sql('my_table', conn))
print(pd.read_sql('SELECT * FROM my_table WHERE 1=1;', conn))

Engine(sqlite:///:memory:)
   index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15
   index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15
